"""added author_id column to DB

Revision ID: be1a2cd7c0a7
Revises: bac0c4276d32
Create Date: 2024-12-01 04:32:47.003771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1a2cd7c0a7'
down_revision: Union[str, None] = 'bac0c4276d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###
